poster_maker_dir: "."  
dataset_dir: "../dataset"
output_dir: "../training_output"
image_size: [1024, 1024]

sd3_model_path: "checkpoints/stable-diffusion-3-medium-diffusers"
scene_gen_net_path: "checkpoints/ours_weights/scenegen_net-0415.pth"
original_textrender_net_path: "checkpoints/ours_weights/textrender_net-0415.pth"

ids_database_path: "./ids/ids_database.txt"
ids_vocab_path: "./assets/ids_vocab.json"
char2feat_path: "assets/char2feat_ppocr_neck64_avg.pth"

stage1:
  learning_rate: 1.0e-8
  batch_size: 1
  gradient_accumulation_steps: 4
  num_train_epochs: 20
  embedding_dim: 64
  max_seq_length: 128
  save_steps: 100  
  validation_steps: 2
  use_amp: true  
  lr_scheduler_type: "cosine"
  max_grad_norm: 0.1
  weight_decay: 0.001  

seed: 42